In [1]:
import numpy as np

In [6]:
python_list = [1,2,3,4,5]
np_array = np.array( python_list )
type(np_array[0])

numpy.int32

In [7]:
np_int64 = np.array( [1,2,3], dtype = np.int64)
type(np_int64[0])

numpy.int64

In [9]:
np.arange(12) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.arange(12).shape

(12,)

In [12]:
t = 12
print(type(t))
t = 12,
print(type(t))
print(t)

<class 'int'>
<class 'tuple'>
(12,)


In [13]:
m = np.arange(12).reshape(3,4); m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np_array % 2 == 0

array([False,  True, False,  True, False])

In [15]:
np_array [np_array <= 3]

array([1, 2, 3])

In [16]:
import numpy as np
np.random.seed(10)
sales = np.array((100 * np.random.rand (5)).astype(int)); sales

array([77,  2, 63, 74, 49])

In [17]:
np.linspace(-5,5,20)

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [18]:
np.diff(np.linspace(-5,5,20) )

array([0.52631579, 0.52631579, 0.52631579, 0.52631579, 0.52631579,
       0.52631579, 0.52631579, 0.52631579, 0.52631579, 0.52631579,
       0.52631579, 0.52631579, 0.52631579, 0.52631579, 0.52631579,
       0.52631579, 0.52631579, 0.52631579, 0.52631579])

In [19]:
np.sum(np.diff(np.linspace(-5,5,20)))

10.0