In [1]:
import numpy as np

In [3]:
python_list = [1,2,3,4,5]
np_array = np.array( python_list )

In [4]:
type(np_array[0])

numpy.int32

In [5]:
np_int64 = np.array( [1,2,3], dtype = np.int64)
type(np_int64[0])

numpy.int64

In [6]:
np.arange(12) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(12).shape

(12,)

In [8]:
t = 12
print(type(t))
t = 12,
print(type(t))
print(t)

<class 'int'>
<class 'tuple'>
(12,)


In [9]:
m = np.arange(12).reshape(3,4); m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
np_array % 2 == 0

array([False,  True, False,  True, False])

In [11]:
np_array [np_array <= 3]

array([1, 2, 3])

In [12]:
import numpy as np
np.random.seed(10)
sales = np.array((100 * np.random.rand (5)).astype(int)); sales

array([77,  2, 63, 74, 49])